name: hitagyana_college_finder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sizer: ^2.0.15
  fluttertoast: ^8.2.6
  shared_preferences: ^2.2.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.3
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/