name: hitagyana_college_finder
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  fluttertoast: ^8.2.8
  sizer: ^2.0.15
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  web: any
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_analytics: ^10.8.0
  google_sign_in: ^6.2.1
  crypto: ^3.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/